# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe43d56920d2746b324f8aab83cedafbd2c7d24ee12a541ae81065c4c2a99f1fdf54202b5faa9129a4e15cd3d8be3a6b9e2dc3216ccdc86c593d38346674a8e9

test:
  secret_key_base: 406da51b19d6d64e0a720e4f7100917780af68c2bb7fc6b76359779546caf1ac173cb262403bec0274ee3444a6873cc659bf6bafad2e9acb662d12ea1e5510ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
